import { Badge, Card, CardTitle, Kpi, PageHeader, fmt } from "@/components/ui";
import { ForecastBand } from "@/components/charts/ForecastBand";
import { BarList, SdkEmpty } from "@/components/sdk";
import { getSdkEventTotals, getSdkForecasts, getSdkInsights } from "@/lib/queries";
import { getTenantId } from "@/lib/tenant";
import { LiveRefresh } from "@/components/LiveRefresh";

export const dynamic = "force-dynamic";

const PILLAR_LABEL: Record<string, string> = {
  "agent.detected": "Detections",
  "auth.identity_presented": "Auth presents",
  "authz.evaluated": "Authz decisions",
  "tool.executed": "Tool calls",
  "memory.accessed": "Memory reads",
  "sdk.error": "Errors"
};

// Light, safe markdown (bold + line breaks) — insight bodies are bounded + model-generated.
function renderBody(md: string) {
  return md.split("\n").map((line, i) => {
    const parts = line.split(/(\*\*[^*]+\*\*)/g).map((seg, j) =>
      seg.startsWith("**") && seg.endsWith("**") ? <strong key={j}>{seg.slice(2, -2)}</strong> : seg
    );
    return <p key={i} style={{ margin: "0 0 6px" }}>{parts}</p>;
  });
}

export default async function AnalyticsPage() {
  const tenantId = await getTenantId();
  const [totals, forecasts, insights] = await Promise.all([
    getSdkEventTotals(tenantId, 30),
    getSdkForecasts(tenantId),
    getSdkInsights(tenantId)
  ]);

  const all = Object.values(totals).reduce((s, n) => s + n, 0);
  const toolCalls = totals["tool.executed"] ?? 0;
  const errors = totals["sdk.error"] ?? 0;
  const eventForecast = forecasts.filter((f) => f.metric === "sdk_events");

  return (
    <>
      <PageHeader title="Analytics" subtitle="Cross-pillar SDK activity, forecasts, and AI insights" action={<LiveRefresh />} />
      {all === 0 ? (
        <SdkEmpty feature="SDK" />
      ) : (
        <>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 14, marginBottom: 18 }}>
            <Kpi label="Total events" value={fmt(all)} sub="all pillars, 30d" />
            <Kpi label="Tool calls" value={fmt(toolCalls)} sub="tool.executed" />
            <Kpi label="Errors" value={fmt(errors)} sub="sdk.error" />
          </div>

          <Card style={{ marginBottom: 18 }}>
            <CardTitle>Events by pillar</CardTitle>
            <BarList
              items={Object.entries(totals)
                .sort((a, b) => b[1] - a[1])
                .map(([type, value]) => ({ label: PILLAR_LABEL[type] ?? type, value }))}
            />
          </Card>

          <Card style={{ marginBottom: 18 }}>
            <CardTitle>Forecast · next 14 days (events)</CardTitle>
            <ForecastBand points={eventForecast} />
          </Card>

          <CardTitle>Insights</CardTitle>
          {insights.length === 0 ? (
            <Card>
              <div style={{ color: "var(--content-muted)", fontSize: 14 }}>
                No insights yet — generated by the daily SDK ML pass once there&apos;s activity to narrate.
              </div>
            </Card>
          ) : (
            <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
              {insights.map((it) => (
                <Card key={it.id}>
                  <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 8, gap: 12 }}>
                    <h3 style={{ margin: 0, fontSize: 16, fontWeight: 700, letterSpacing: "-0.01em" }}>{it.title}</h3>
                    <Badge kind={it.severity}>{it.severity}</Badge>
                  </div>
                  <div style={{ fontSize: 14, color: "var(--content-secondary)", lineHeight: 1.55 }}>{renderBody(it.body_md)}</div>
                  <div style={{ marginTop: 10, fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--content-muted)" }}>
                    {it.kind} · {new Date(it.created_at as unknown as string).toLocaleString()}
                  </div>
                </Card>
              ))}
            </div>
          )}
        </>
      )}
    </>
  );
}
