// Agentronics brand logomark — the "A" (indigo apex cap + left leg with a
// detached amber lower-right leg). Geometry is generated by
// landing_page/scripts/brand/build_logo.py (the single source of truth) — copy
// the paths from there rather than editing them here. Brand colours are baked
// so it reads on light and dark alike; `onDark` is accepted for API compatibility.

const INDIGO = "#5b4fd1";
const AMBER = "#e58313";
const MARK_INDIGO =
  "M66.63 0L74.11 0A10.37 10.37 0 0 1 83.39 5.73L98.03 35.02A2.59 2.59 0 0 1 95.71 38.77L76.57 38.77A10.37 10.37 0 0 0 67.72 43.76L36.55 95.02A10.37 10.37 0 0 1 27.69 100L4.61 100A2.59 2.59 0 0 1 2.39 96.06L57.77 4.98A10.37 10.37 0 0 1 66.63 0Z";
const MARK_AMBER =
  "M82.3 59.36L102.83 59.36A10.37 10.37 0 0 1 112.11 65.09L127.69 96.25A2.59 2.59 0 0 1 125.37 100L104.83 100A10.37 10.37 0 0 1 95.56 94.27L79.98 63.11A2.59 2.59 0 0 1 82.3 59.36Z";
// 5.5 units of padding keep `size` the same visual size as the previous mark.
const PAD = 5.5;
const VB_W = 129.56 + PAD * 2;
const VB_H = 100 + PAD * 2;

export function Logomark({ size = 26, onDark: _onDark = false }: { size?: number; onDark?: boolean }) {
  return (
    <svg
      width={(size * VB_W) / VB_H}
      height={size}
      viewBox={`${-PAD} ${-PAD} ${VB_W} ${VB_H}`}
      fill="none"
      role="img"
      aria-label="Agentronics"
      style={{ flex: "none" }}
    >
      <path d={MARK_INDIGO} fill={INDIGO} />
      <path d={MARK_AMBER} fill={AMBER} />
    </svg>
  );
}
